brain_two/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("todos/", include("todos.urls")),
]

todos/urls.py
from django.urls import path

from todos.views import (
    TodoListView,
    TodoDetailView,
    TodoCreateView,
    TodoUpdateView,
    TodoDeleteView,
    TodoCreateItem,
    TodoUpdateItem,
)


urlpatterns = [
    path("", TodoListView.as_view(), name="todo_list_list"),
    path("<int:pk>/", TodoDetailView.as_view(), name="todo_list_detail"),
    path("create/", TodoCreateView.as_view(), name="todo_list_create"),
    path("<int:pk>/edit/", TodoUpdateView.as_view(), name="todo_list_update"),
    path("<int:pk>/delete/", TodoDeleteView.as_view(), name="todo_list_delete"),
    path("items/create/", TodoCreateItem.as_view(), name="todo_item_create"),
    path(
        "items/<int:pk>/edit/",
        TodoUpdateItem.as_view(),
        name="todo_item_update",
    ),
]

todos/models.py
from django.db import models
from django.conf import settings
from django.db.models import Model

# Create your models here.
class TodoList(models.Model):
    name = models.CharField(max_length=100)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class TodoItem(models.Model):
    task = models.CharField(max_length=100)
    due_date = models.DateTimeField(null=True, blank=True)
    is_completed = models.BooleanField(default=False)
    list = models.ForeignKey(
        "TodoList", related_name="items", on_delete=models.CASCADE
    )

    def __str__(self):
        return self.task

todos/views.py
# from django.shortcuts import render
from django.views.generic.list import ListView
from todos.models import TodoList, TodoItem
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.shortcuts import redirect

# Create your views here.
class TodoListView(ListView):
    model = TodoList
    template_name = "todos/list.html"


class TodoDetailView(DetailView):
    model = TodoList
    template_name = "todos/detail.html"


class TodoCreateView(CreateView):
    model = TodoList
    template_name = "todos/create.html"
    fields = ["name"]

    def get_success_url(self):
        return reverse_lazy("todo_list_detail", args=[self.object.id])


class TodoUpdateView(UpdateView):
    model = TodoList
    template_name = "todos/update.html"
    fields = ["name"]

    def get_success_url(self):
        return reverse_lazy("todo_list_detail", args=[self.object.id])


class TodoDeleteView(DeleteView):
    model = TodoList
    template_name = "todos/delete.html"
    success_url = reverse_lazy("todo_list_list")


class TodoCreateItem(CreateView):
    model = TodoItem
    template_name = "todos/new.html"
    fields = ["task", "due_date", "is_completed", "list"]
    success_url = reverse_lazy("todo_list_list")

    def get_success_url(self):
        return reverse_lazy("todo_list_detail", args=[self.object.list.id])


class TodoUpdateItem(UpdateView):
    model = TodoItem
    template_name = "todos/updateitem.html"
    fields = ["task", "due_date", "is_completed", "list"]

    def get_success_url(self):
        return reverse_lazy("todo_list_detail", args=[self.object.id])

todos/templates/todos/create.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Create a Todo</title>
</head>
<body>
    <main>
        <div>
            <h1>Create a new list</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <div>
                    <button>Create</button>
                </div>
            </form>
        </div>
    </main>
</body>
</html>

todos/templates/todos/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Delete</title>
</head>
<body>
    <main>
        <div>
            <h1>Are you sure?</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <div>
                    <button>Delete</button>
                </div>
            </form>
        </div>
    </main>
</body>
</html>

todos/templates/todos/detail.html
<!DOCTYPE html>
<html>
    <head>
        <title></title>
        <link rel="stylesheet" href="">
    </head>
    <body>
        <main>
            <div>
                <h1>{{todolist.name}}</h1>
                <p>
                    <a href="{% url 'todo_list_update' todolist.pk %}">Edit</a>
                </p>
                <p>
                    <a href="{% url 'todo_list_delete' todolist.pk %}">Delete</a>
                </p>
                <h2>Tasks</h2>
                <table>
                    <thead>
                        <th>Task</th>
                        <th>Due date</th>
                    </thead>
                    <tbody>
                        {% for t in todolist.items.all %}
                        <tr>
                            <td>
                                <a href="{% url 'todo_item_update' todolist.pk %}">{{t.task}}</a>
                            </td>
                            <td>{{t.due_date}}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </main>
    </body>
</html>

todos/templates/todos/list.html
<!DOCTYPE html>
<html>
    <head>
        <title></title>
        <link rel="stylesheet" href="">
    </head>
    <body>
        <main>
            <div>
                <h1>My Lists</h1>
                <p>
                    <a href="{% url 'todo_list_create' %}">Create a new list</a>
                </p>
                <p>
                    <a href="{% url 'todo_item_create' %}">Create a new item</a>
                </p>
                        <table>
                            <thead>
                                    <th>Name</th>
                                    <th>Number of Items</th>
                            </thead>
                            <tbody>
                                {% for n in todolist_list %}
                                    <tr>
                                        <td>
                                            <a href="{% url 'todo_list_detail' n.pk %}">{{n.name}}</a>
                                        </td>
                                        <td>
                                            {{n.items.all|length}}
                                        </td>
                                    </tr>
                                    {% endfor %}
                            </tbody>
                        </table>
            </div>
        </main>
    </body>
</html>

todos/templates/todos/new.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Item</title>
</head>
<body>
    <main>
        <div>
            <h1>Create a new item</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <div>
                    <button>Create</button>
                </div>
            </form>
        </div>
    </main>
</body>
</html>

todos/templates/todos/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Update!</title>
</head>
<body>
    <main>
        <div>
            <h1>Update list</h1>
            <form method="post">
                {%csrf_token%}
                {{ form.as_p }}
                <div>
                    <button>Update</button>
                </div>
            </form>
        </div>
    </main>
</body>
</html>

todos/templates/todos/updateitem.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Update Item</title>
</head>
<body>
    <main>
        <div>
            <h1>Update Item</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <div>
                    <button>Update</button>
                </div>
            </form>
        </div>
    </main>
</body>
</html>